package controller;

import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.ComboBox;
import javafx.scene.control.TextField;
import service.WorkoutService;
import model.StrengthWorkout;

import java.io.IOException;
import java.time.LocalDate;

public class LogStrengthController {

    // --- FXML Fields (Match LogStrength.fxml) ---
    @FXML private Button backButton;
    @FXML private Button profileButton;
    @FXML private ComboBox<String> exerciseComboBox;
    @FXML private TextField setsField;
    @FXML private TextField repsField;
    @FXML private TextField weightField;
    @FXML private Button saveWorkoutButton;
    
    // --- Navigation Buttons ---
    @FXML private Button summaryNavButton;
    @FXML private Button homeNavButton;
    @FXML private Button goalsNavButton;

    // Connect to the backend service
    private final WorkoutService workoutService = new WorkoutService();

    @FXML
    public void initialize() {
        loadExercises();
        setupEventHandlers();
    }

    private void loadExercises() {
        // You can add more exercises here or load them from the database later
        exerciseComboBox.getItems().addAll(
            "Bicep Curls",
            "Preacher Curls",
            "Bench Press",
            "Squats",
            "Deadlift",
            "Shoulder Press",
            "Pull-ups",
            "Push-ups"
        );
    }

    private void setupEventHandlers() {
        // --- Action Buttons ---
        backButton.setOnAction(e -> navigate("LogSelection"));
        profileButton.setOnAction(e -> navigate("EditProfile"));
        saveWorkoutButton.setOnAction(e -> saveWorkout());
        
        // --- Bottom Navigation Bar ---
        homeNavButton.setOnAction(e -> navigate("MainDashboard"));
        summaryNavButton.setOnAction(e -> navigate("ProgressReport"));
        goalsNavButton.setOnAction(e -> navigate("SetGoal"));
    }

    private void saveWorkout() {
        String exercise = exerciseComboBox.getValue();
        String setsText = setsField.getText();
        String repsText = repsField.getText();
        String weightText = weightField.getText();

        // Basic Validation
        if (exercise == null || setsText.isEmpty() || repsText.isEmpty() || weightText.isEmpty()) {
            System.out.println("Please fill in all fields.");
            return;
        }

        try {
            int sets = Integer.parseInt(setsText);
            int reps = Integer.parseInt(repsText);
            double weight = Double.parseDouble(weightText);

            // Calculations
            double volume = sets * reps * weight;
            
            // Estimation (Since inputs are missing in this simple form): 
            // Assume ~3 minutes per set (including rest)
            int estimatedDuration = sets * 3; 
            // Rough estimate: 3.5 calories per minute of strength training
            double estimatedCalories = estimatedDuration * 3.5; 

            StrengthWorkout workout = new StrengthWorkout(
                0,                  // ID (Auto-generated by DB)
                exercise,           // Name
                "Strength",         // Type
                LocalDate.now(),    // Date
                estimatedCalories,  // Calories
                estimatedDuration,  // Duration
                sets,               // Sets
                reps,               // Reps
                weight,             // Weight
                volume,             // Volume
                0.0                 // BodyWeight Factor (default)
            );

            // Save to Database
            boolean success = workoutService.logWorkout(workout);

            if (success) {
                // Check for Personal Record (heaviest weight lifted)
                workoutService.checkPersonalRecord(exercise, weight, reps, estimatedDuration);
                
                System.out.println("Strength workout saved!");
                clearFields();
                navigate("MainDashboard");
            } else {
                System.err.println("Failed to save workout.");
            }

        } catch (NumberFormatException e) {
            System.out.println("Invalid number format. Please enter numbers for Sets, Reps, and Weight.");
        }
    }

    private void clearFields() {
        exerciseComboBox.setValue(null);
        setsField.clear();
        repsField.clear();
        weightField.clear();
    }

    // Helper method to use your Main.setRoot navigation safely
    private void navigate(String fxml) {
        try {
            Main.setRoot(fxml);
        } catch (IOException e) {
            e.printStackTrace();
            System.err.println("Error navigating to " + fxml);
        }
    }
}